name: cd github workflow

on:
  push:
    branches:
      - master

jobs:
  echo-cd:
    runs-on: ubuntu-latest
    steps:
      - run: echo "echo cd workflow"

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: QEMU setup
        uses: docker/setup-qemu-action@v1
      - name: docker build setup
        uses: docker/setup-buildx-action@v1
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: image build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ivanauliaa/go-appointment:latest
      - name: ssh aws ec2 then update docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/app/api
            docker-compose down
            docker image rm ivanauliaa/go-appointment:latest
            docker-compose up -d
